-- Recuperação: os 14 livros seed foram apagados pelo botão "Apagar" do painel admin
-- (que remove a linha em books; os EPUBs/capas ficaram no R2). Como o Apagar é
-- irreversível e o "Despublicar" já cobre o caso de esconder um livro, re-inserimos
-- aqui os dados originais. Valores finais já mesclados: pages/mins/rating de
-- publish_books, cover_path de covers (2 sem capa → NULL, fallback tipográfico),
-- e géneros já na taxonomia PT (Thriller→Suspense, Auto-ajuda→Des. Pessoal, Drama→Romance).
-- epub_path = nome real do ficheiro no bucket privado zuri-books (alguns truncados).
--
-- on conflict (id) do nothing: restaura só o que falta, não sobrescreve sobreviventes.

insert into public.books (id, title, author, genre, synopsis, epub_path, cover_path, pages, mins, rating, is_published) values
('a-ex', 'A Ex', 'Freida McFadden', 'Suspense', 'Cassie pensa que encontrou o homem perfeito. Mas a sombra da ex dele, Francesca — bela, brilhante e adorada por todos — paira sobre a relação. À medida que os segredos se revelam, o perigo torna-se real.', 'a-ex.epub', 'covers/a-ex.jpg', 320, 400, 4.6, true),
('a-pessoa-certa-e-voce', 'A Pessoa Certa És Tu', 'Sheleana Aiyana', 'Des. Pessoal', 'Um guia transformador para acabar com o ciclo de auto-abandono. A fundadora da comunidade Rising Woman oferece ferramentas práticas para curar traumas e transformar padrões de relacionamento.', 'a-pessoa-certa-e-voce.epub', 'covers/a-pessoa-certa-e-voce.jpg', 280, 350, 4.4, true),
('alem-da-tempestade', 'Além da Tempestade', 'Cecelia Ahern', 'Romance', 'Da autora best-seller de P.S. Eu Te Amo, uma história envolvente sobre autodescoberta. Personagens à beira do precipício descobrem que as maiores tempestades são as que carregamos por dentro.', 'alem-da-tempestade.epub', 'covers/alem-da-tempestade.jpg', 340, 430, 4.5, true),
('como-arruinar-um-casamento', 'Como Arruinar um Casamento', 'Alison Espach', 'Ficção', 'Phoebe Stone chega a um luxuoso resort e é confundida com convidada de um casamento. Uma história comovente sobre amizades improváveis entre duas mulheres em fases muito diferentes da vida.', 'como-arruinar-um-casamento.epub', NULL, 310, 390, 4.3, true),
('ninguem-nasce-sabendo', 'Ninguém Nasce Sabendo', 'Thomas Schultz', 'Des. Pessoal', 'Um guia prático para quem quer relacionamentos extraordinários. O psicólogo Thomas Schultz partilha ferramentas baseadas na prática clínica para construir ligações mais saudáveis e duradouras.', 'ninguem-nasce-sabendo.epub', 'covers/ninguem-nasce-sabendo.png', 220, 275, 4.2, true),
('no-rastro-da-mentira', 'No Rastro da Mentira', 'Amy Tintera', 'Suspense', 'Lucy é encontrada coberta de sangue da sua melhor amiga Savvy. Um podcaster de crime verdadeiro investiga o caso e, à medida que os factos se acumulam, a verdade revela-se mais perturbadora do que o esperado.', 'no-rastro-da-mentira.epub', 'covers/no-rastro-da-mentira.jpg', 380, 475, 4.5, true),
('nao-comecou-com-voce', 'Não Começou com Você', 'Mark Wolynn', 'Des. Pessoal', 'Como o trauma familiar herdado nos define — e como quebrar esse ciclo. Wolynn apresenta técnicas práticas para compreender e superar padrões transmitidos de geração em geração.', 'nao-comecou-com-voce.epub', 'covers/nao-comecou-com-voce.jpg', 260, 325, 4.6, true),
('nos-ja-moramos-aqui', 'Nós Já Moramos Aqui', 'Marcus Kliewer', 'Suspense', 'Charlie e Eve compram uma casa antiga no Oregon e começam a receber a visita de estranhos que alegam ter vivido lá. Eventos inexplicáveis criam uma tensão crescente que desafia a realidade.', 'nos-ja-moramos-aqui.epub', 'covers/nos-ja-moramos-aqui.jpg', 290, 365, 4.3, true),
('o-diabo-veste-cor-de-rosa', 'O Diabo Veste Cor-de-Rosa', 'Alexandria Bellefleur', 'Romance', 'Sam fica presa num elevador com Daphne, uma bela demónia vestida de rosa. Quando Daphne oferece seis desejos, uma comédia romântica sáfica irresistível começa a desenrolar-se.', 'o-diabo-veste-cor-de-rosa.epub', 'covers/o-diabo-veste-cor-de-rosa.jpg', 300, 375, 4.4, true),
('por-que-as-mulheres-amam-homens-fortes', 'Por que as Mulheres Amam os Homens Fortes', 'Elliott Katz', 'Des. Pessoal', 'O que as mulheres realmente procuram: um homem confiável, protetor e decisivo. Um guia com conselhos práticos para melhorar relacionamentos e restaurar o respeito mútuo.', 'por-que-as-mulheres-amam-os-homens-fortes.epub', 'covers/por-que-as-mulheres-amam-os-homens-fortes.jpg', 180, 225, 4.0, true),
('por-que-ninguem-me-disse-isso-antes', 'Por que Ninguém Me Disse Isso Antes', 'Julie Smith', 'Des. Pessoal', 'A psicóloga clínica Julie Smith oferece ferramentas práticas para compreender sentimentos e padrões comportamentais. Um guia acessível para lidar com os altos e baixos inevitáveis da vida.', 'por-que-ninguem-me-disse-isso-a.epub', 'covers/por-que-ninguem-me-disse-isso-a.jpg', 300, 375, 4.7, true),
('sem-chance-de-adeus', 'Sem Chance de Adeus', 'Harlan Coben', 'Suspense', 'Maggie McCabe, cirurgiã militar, recebe uma proposta que muda tudo. Uma parceria improvável com um cirurgião plástico leva-a a desvendar segredos enterrados há décadas — e a enfrentar o perigo de frente.', 'sem-chance-de-adeus.epub', NULL, 360, 450, 4.5, true),
('um-crush-dos-infernos', 'Um Crush dos Infernos', 'Charlotte Ingham', 'Romance', 'Willow White morre aos 21 anos e desperta em Asfódelos, uma dimensão infernal. Para regressar à vida, deve completar sete missões — enquanto lida com sentimentos inesperados por quem nunca esperava.', 'um-crush-dos-infernos.epub', 'covers/um-crush-dos-infernos.jpg', 340, 425, 4.3, true),
('um-namorado-bom-pra-cachorro', 'Um Namorado Bom pra Cachorro', 'Brittainy Cherry', 'Romance', 'Yara, recém-divorciada, surpreende-se quando Alex concorda em fingir ser o seu namorado. Uma história sobre como o fingimento pode tornar-se genuinamente real — e como isso muda tudo.', 'um-namorado-bom-pra-cachorro.epub', 'covers/um-namorado-bom-pra-cachorro.jpg', 310, 390, 4.4, true)
on conflict (id) do nothing;
